#spring:
#  application:
#    name: damai-eureka
#
#server:
#  port: 8762
#eureka:
#  client:
#    # 下面这个两个一般在 eureka 集群中使用, 单机eureka不用配
#    # 是否注册自己
#    registerWithEureka: false
#    # 检索注册信息
#    fetchRegistry: false
